"""added hashed_password and disabled columns to the users table

Revision ID: 69a1d0a9e1cf
Revises: d93998fbdfca
Create Date: 2025-12-26 12:38:19.770418

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69a1d0a9e1cf"
down_revision: str | Sequence[str] | None = "d93998fbdfca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("disabled", sa.Boolean(), nullable=False, server_default="0")
    )
    op.add_column(
        "users",
        sa.Column("hashed_password", sa.Text(), nullable=False, server_default=""),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "disabled")
    # ### end Alembic commands ###
