"""add tags to habits table

Revision ID: a8f30d9d343d
Revises: 6a7fef1e6614
Create Date: 2026-02-21 10:40:03.876006

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8f30d9d343d"
down_revision: str | Sequence[str] | None = "6a7fef1e6614"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("habits", sa.Column("tags", sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("habits", "tags")
    # ### end Alembic commands ###
