"""Rename user_name to username

Revision ID: 71e059a1ab6b
Revises: 69a1d0a9e1cf
Create Date: 2026-01-01 19:04:06.701312

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71e059a1ab6b"
down_revision: str | Sequence[str] | None = "69a1d0a9e1cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.VARCHAR(), nullable=True))
    # op.execute("UPDATE users SET username = user_name") <-wasnt performed, so it set
    # all usernames to NULL
    op.drop_column("users", "user_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("user_name", sa.VARCHAR(), nullable=True))
    op.drop_column("users", "username")
    # ### end Alembic commands ###
